### ISSUE TITLE
Improve smoothing speed

### ISSUE THREAD

**Issue by babaf** [mattperich/PyalData#101]
we could use 
https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.convolve1d.html

which makes smoothing along one axis much faster I think than looping

**Comment by raeedcho** [comment]
This change somehow makes smoothing run slower than before on my computer, but I'm not sure how that could be the case if it works faster for everyone else. For one of my datasets, running `%timeit pyaldata.add_firing_rates(td,'smooth',std=0.05)` now gives 18.7 s ± 52.8 ms, whereas if I revert the change, it gives 4.55 s ± 113 ms.
