### ISSUE TITLE
Smoothing functions applied to spike data result in still-jagged outputs

### ISSUE THREAD

**Issue by raeedcho** [mattperich/PyalData#116]
Applying any of the available smoothing functions (anything that uses `util.norm_gaussian_window`) to spike data seems to result in slightly jagged output (example image below)

![image](https://user-images.githubusercontent.com/1281391/129418760-054f0cc0-437d-4452-bc97-4d0a116502d0.png)

I'm pretty sure this is because the default window for `util.norm_gaussian_window` is 5 standard deviations long, which results in tails that aren't at zero (see below)

![image](https://user-images.githubusercontent.com/1281391/129418891-261b31cd-a863-4cf3-a471-0fc24aee151e.png)

I propose we increase the length of the default window to 10 standard deviations long, which seems to get rid of the jaggedness for me.

![image](https://user-images.githubusercontent.com/1281391/129418960-f10704bb-328f-4a64-8133-8dfb636503b9.png)

![image](https://user-images.githubusercontent.com/1281391/129418979-2037d2c8-6150-49e5-8e6c-332e23039e00.png)

**Comment by bagibence** [comment]
Good catch, makes sense, merged the PR. Thank you! 👍
