### ISSUE TITLE
mat2dataframe does not work for all data sets 

### ISSUE THREAD

**Issue by catiafortunato** [mattperich/PyalData#49]
I get an error when trying to load mat files that were not saved in matlab as "trial_data".

**Comment by bagibence** [comment]
What does `scipy.io.loadmat(filename, simplify_cells=True).keys()` return? Are they still saved under a single name?

For me it's always `dict_keys(['__header__', '__version__', '__globals__', 'trial_data'])`. It would be nice if it's similar and there's only one "real" key.

**Comment by catiafortunato** [comment]
This is what I got `dict_keys(['__header__', '__version__', '__globals__', 'new_ss'])`

They are still saved under a single name, but it depends on the name of the variable in matlab.

**Comment by bagibence** [comment]
Great! I'll post a fix in a few minutes. Do we want to rename it to `mat2df` while we're at it or do you like `mat2dataframe` better?

**Comment by bagibence** [comment]
@catiafortunato does #53 fix it?

**Comment by catiafortunato** [comment]
It does, yes!
