### ISSUE TITLE
Add info about how many neurons were removed in remove_low_firing_neurons

### ISSUE THREAD

**Issue by babaf** [mattperich/PyalData#68]
It would be nice if `remove_low_firing_neurons` prints how many neurons where removed.
I know that I can obviously check it myself, I just think it would be a nice extra (because you often want to report this in your paper etc.).

**Comment by bagibence** [comment]
Yes, that would be nice! Would you mind implementing it? :)

**Comment by bagibence** [comment]
@babaf how about this `verbose` option?
