### ISSUE TITLE
Handle NaN values in trial timing lists

### ISSUE THREAD

**Issue by babaf** [mattperich/PyalData#69]
There are sometime NaN values for specific events, such as movement onset.
If this is the case the timing list will be float, not int and this will cause problems in the slicing method.

**Comment by babaf** [comment]
cmp. Chewie_CO_FF_2016-10-11 td.loc[693,'idx_movement_on']

**Comment by bagibence** [comment]
Thanks for pointing this out! I just noticed this last week but forgot about it. I'm not sure what would be the right way to deal with this.

One solution is to drop the trials with the NaN values, then convert the column to have dtype `int`. (I guess NaNs usually happen on failed trials and in many analyses we want to drop those anyway.)
Another, if we want to keep the NaNs and convert the others to `int`, is to set the column's type to `object`. I guess this should work if every operation happens trial-wise, but calling e.g. `np.isnan(td[column_name])` won't work anymore. (A possible workaround could be `np.isnan(td[column_name].astype(float))`)

Maybe have a `clean_idx_fields` function that lets you choose? Or other suggestions?

**Comment by babaf** [comment]
I wouldn't want the dtype `object` I think, couldn't this potentially mess up things if there is no consistent data type for those indeces?? Maybe we can set it to -1 or so, which then would be a flag for nan but would still fit to `int` data type??

`clean_idx_fields` is a nice idea I think!

**Comment by AtMostafa** [comment]
This is also solved by #105
