### ISSUE TITLE
Remove and rename functions

### ISSUE THREAD

**Issue by bagibence** [mattperich/PyalData#75]
- [ ] remove old functions whose functionality is implemented in newer ones

- [ ] Also `get_signals` could be renamed to `get_sig` to be shorter and consistent with `get_sig_by_trial`. Since it's like a smarter version of `concat_trials`, `concat_trials` could be renamed to something like `_concat_trials` to show that it's mainly for internal use. Then promote the use of `get_sig` in the demo as well.

**Comment by bagibence** [comment]
Old functions in tools: `getTDidx`, `projLow`
Old functions in utils: `getSig`, `dimReduce`

I'm not sure about `binTD`. @catiafortunato is that the same as `combine_time_bins`?
Also not sure about `truncTD`. Is that replaced by `restrict_to_interval` or not?

**Comment by catiafortunato** [comment]
`binTD` is the same as `combine_time_bins` and `truncTD` is replaced by `restrict_to_interval`
