### ISSUE TITLE
positional argument in restrict_to_interval

### ISSUE THREAD

**Issue by AtMostafa** [mattperich/PyalData#84]
the error below happens only if the first argument (trial_data) is specified as a keyword. I think there is an assumption that the first argument will always be positional :)
![image](https://user-images.githubusercontent.com/9393635/109795577-febb3480-7c0e-11eb-8531-9bd58b04c5b0.png)

**Comment by bagibence** [comment]
Yes, that's exactly it. Do you have a preference for passing it as a keyword argument?

**Comment by AtMostafa** [comment]
Just being explicit. 
I copied the function signature from where it was defined (which is what I always do to avoid mistakes) and that's how this error happened.

**Comment by bagibence** [comment]
Okay. We can fix it, we just have to put another check in the decorator.
Do you want to fix this as your first PR? Or I can do it when I get around to it :)

**Comment by bagibence** [comment]
@AtMostafa can you check if this works for you?
