### ISSUE TITLE
Not requiring spikes

### ISSUE THREAD

**Issue by JoannaChang** [mattperich/PyalData#89]
I am working with simulated data that only has rates, but some of the functions (e.g. get_time_varying_fields and other functions that use it like trial_average) require the data to have spikes. Right now, I have "spikes" columns filled with NaNs. Is it possible to change the functions so that it can look for rates if spikes are absent?

**Comment by bagibence** [comment]
Yes, definitely. Ultimately the user should be able to specify the reference time-varying field everywhere.
