### ISSUE TITLE
Possible bug with newer pandas version for trial_average

### ISSUE THREAD

**Issue by JoannaChang** [mattperich/PyalData#90]
I originally had pandas 1.1.1 and everything worked fine. When I updated to pandas 1.2.3, trial_average no longer averaged columns with series (e.g. spikes, rates, etc). In the new pandas documentation, it specifies that it won't compute the mean on series in a dataframe: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.mean.html.

**Comment by raeedcho** [comment]
I think there's already a pull request related to this in the works (https://github.com/mattperich/PyalData/pull/88#issue-594176506)

**Comment by bagibence** [comment]
Exactly.
@JoannaChang can you check if that PR works for you? If it does, I'll merge it.
